[package]
name = "glfw_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl33 = "0.2.1"
glfw = "0.52.0"
image = "0.24.6"
nalgebra-glm = "0.18.0"
